export const sample_foods = [
    {
      id: '1',
      name: 'Pizza Pepperoni',
      cookTime: '10-20',
      price: 209.99,
      favorite: true,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'food-1.jpg',
      tags: ['FastFood', 'Starter'],
    },
    {
      id: '2',
      name: 'Fried Rice',
      price: 345.99,
      cookTime: '15-20',
      favorite: false,
      origins: ['persia', 'middle east', 'china'],
      stars: 5,
      imageUrl: 'food-2.jpg',
      tags: ['Main_Course', 'Lunch'],
    },
    {
      id: '3',
      name: 'Burger',
      price: 215.00,
      cookTime: '10-15',
      favorite: true,
      origins: ['germany', 'us'],
      stars: 3.5,
      imageUrl: 'food-3.webp',
      tags: ['FastFood', 'Starter'],
    },
    {
      id: '4',
      name: 'French-Fry',
      price: 89.99,
      cookTime: '5-10',
      favorite: false,
      origins: ['belgium', 'france'],
      stars: 3,
      imageUrl: 'food-4.jpg',
      tags: ['FastFood', 'Fry', 'Starter'],
    },
    {
      id: '5',
      name: 'Chicken Soup',
      price: 110.00,
      cookTime: '10-20',
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.5,
      imageUrl: 'food-5.jpg',
      tags: ['SlowFood', 'Soup', 'Starter'],
    },
    {
      id: '6',
      name: 'Noodles',
      price: 250.99,
      cookTime: '15-20',
      favorite: true,
      origins: ['Korea'],
      stars: 4.0,
      imageUrl: 'food-6.jpeg',
      tags: ['Main_Course', 'Lunch'],
    },
    {
      id: '7',
      name: 'Chicken Biriyani',
      price: 350.99,
      cookTime: '10-15',
      favorite: true,
      origins: ['India'],
      stars: 4.5,
      imageUrl: 'food-7.jpg',
      tags: ['Main_Course', 'Lunch'],
    },
    {
      id: '8',
      name: 'ice-cream sundae',
      price: 210.00,
      cookTime: '10-15',
      favorite: true,
      origins: ['France'],
      stars: 4.5,
      imageUrl: 'food-8.jpg',
      tags: ['SlowFood', 'Desert'],
    },
    {
      id: '9',
      name: 'Barbecued Chicken Kabab',
      price: 240.00,
      cookTime: '10-20',
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.5,
      imageUrl: 'food-9.jpg',
      tags: ['SlowFood', 'Starter'],
    },
    {
      id: '10',
      name: 'Chicken Tikka Masala',
      price: 440.00,
      cookTime: '15-25',
      favorite: true,
      origins: ['India'],
      stars: 4.5,
      imageUrl: 'food-10.jpg',
      tags: ['Main_Course', 'Lunch'],
    },
    {
      id: '11',
      name: 'Mocktails',
      price: 120.00,
      cookTime: '5-10',
      favorite: true,
      origins: ['France'],
      stars: 3.8,
      imageUrl: 'food-11.jpg',
      tags: ['SlowFood', 'Desert'],
    },
    {
      id: '12',
      name: 'Kashmiri Mutton Curry',
      price: 440.00,
      cookTime: '15-25',
      favorite: true,
      origins: ['India'],
      stars: 4.5,
      imageUrl: 'food-12.jpg',
      tags: ['Main_Course', 'Lunch'],
    },
    {
      id: '13',
      name: 'Momos',
      price: 100.00,
      cookTime: '5-10',
      favorite: true,
      origins: ['India'],
      stars: 4.0,
      imageUrl: 'food-13.jpg',
      tags: ['Starter'],
    },
    {
      id: '14',
      name: 'Chili Chicken',
      price: 210.00,
      cookTime: '10-20',
      favorite: true,
      origins: ['India'],
      stars: 3.5,
      imageUrl: 'food-14.jpg',
      tags: ['Main_Course'],
    },
    {
      id: '15',
      name: 'Black-Forest Pestry',
      price: 60.00,
      cookTime: '5-7',
      favorite: true,
      origins: ['India'],
      stars: 4.0,
      imageUrl: 'food-15.jpg',
      tags: ['Desert'],
    },
    {
      id: '16',
      name: 'Egg Chicken Rolls',
      price: 80.00,
      cookTime: '10-15',
      favorite: false,
      origins: ['India'],
      stars: 3.5,
      imageUrl: 'food-16.jpg',
      tags: ['Starter'],
    },
    {
      id: '17',
      name: 'Mutton Hyderabadi Biriyani',
      price: 400.00,
      cookTime: '10-20',
      favorite: true,
      origins: ['India'],
      stars: 4.5,
      imageUrl: 'food-17.jpg',
      tags: ['Main_Course', 'Biriyani'],
    },
    {
      id: '18',
      name: 'Paneer Tikka Masala',
      price: 180.00,
      cookTime: '10-20',
      favorite: false,
      origins: ['India'],
      stars: 3.5,
      imageUrl: 'food-18.webp',
      tags: ['Main_Course'],
    },
    {
      id: '19',
      name: 'Navratan Polao',
      price: 249.99,
      cookTime: '10-20',
      favorite: true,
      origins: ['India'],
      stars: 4.0,
      imageUrl: 'food-19.jpeg',
      tags: ['Main_Course'],
    },
    {
      id: '20',
      name: 'Pepsi',
      price: 50.00,
      cookTime: '05-07',
      favorite: false,
      origins: ['India'],
      stars: 3.0,
      imageUrl: 'food-20.jpeg',
      tags: ['Desert'],
    },
    
  ];
  
  export const sample_tags = [
    { name: 'All', count: 16 },
    { name: 'Ice Cream', count: 4 },
    { name: 'Starter', count: 4 },
    { name: 'Fry', count: 1 },
    { name: 'Biriyani', count: 2 },
    { name: 'Main_Course', count: 1 },
    { name: 'Desert', count: 1 },
    { name: 'Chicken Recipes', count: 1 },
  ];
  
  export const sample_users = [
    {
      id: 1,
      name: 'Sushreta Som',
      email: 'sush@gmail.com',
      password: '12345',
      address: 'Kolkata, India',
      isAdmin: false,
    },
    {
      id: 2,
      name: 'Rubita Som',
      email: 'rubi@gmail.com',
      password: '12345',
      address: 'West Bengal, India',
      isAdmin: true,
    },
  ];